CREATE TABLE IF NOT EXISTS Films
(
    film_id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar NOT NULL,
    description  varchar NULL,
    release_date date    NOT NULL,
    duration     int     NOT NULL,
    rating_id    int     NOT NULL,
    CONSTRAINT pk_Films PRIMARY KEY (
                                     film_id
        )
);

CREATE TABLE IF NOT EXISTS Users
(
    user_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar NOT NULL,
    login    varchar NOT NULL,
    name     varchar NOT NULL,
    birthday date    NOT NULL,
    CONSTRAINT pk_Users PRIMARY KEY (
                                     user_id
        )
);

CREATE TABLE IF NOT EXISTS Friendship_status
(
    status_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      varchar NOT NULL,
    CONSTRAINT pk_Friendship_status PRIMARY KEY (
                                                 status_id
        )
);

CREATE TABLE IF NOT EXISTS Genres
(
    genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar NOT NULL,
    CONSTRAINT pk_Genres PRIMARY KEY (
                                      genre_id
        )
);

CREATE TABLE IF NOT EXISTS Rating
(
    rating_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      varchar NOT NULL,
    CONSTRAINT pk_Rating PRIMARY KEY (
                                      rating_id
        )
);

CREATE TABLE IF NOT EXISTS Friendship
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   int NOT NULL,
    friend_id int NOT NULL,
    status_id int NOT NULL
);

CREATE TABLE IF NOT EXISTS Film_genre
(
    id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id  int NOT NULL,
    genre_id int NOT NULL

);

CREATE TABLE IF NOT EXISTS Film_likes
(
    id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id int NOT NULL,
    user_id int NOT NULL,
    CONSTRAINT pk_Film_likes PRIMARY KEY (
                                          id
        )
);

ALTER TABLE Films
    ADD CONSTRAINT IF NOT EXISTS fk_Films_rating_id FOREIGN KEY (rating_id)
        REFERENCES Rating (rating_id);

ALTER TABLE Friendship
    ADD CONSTRAINT IF NOT EXISTS fk_Friendship_user_id FOREIGN KEY (user_id)
        REFERENCES Users (user_id);

ALTER TABLE Friendship
    ADD CONSTRAINT IF NOT EXISTS fk_Friendship_friend_id FOREIGN KEY (friend_id)
        REFERENCES Users (user_id);

ALTER TABLE Friendship
    ADD CONSTRAINT IF NOT EXISTS fk_Friendship_status_id FOREIGN KEY (status_id)
        REFERENCES Friendship_status (status_id);

ALTER TABLE Film_genre
    ADD CONSTRAINT IF NOT EXISTS fk_Film_genre_film_id FOREIGN KEY (film_id)
        REFERENCES Films (film_id);

ALTER TABLE Film_genre
    ADD CONSTRAINT IF NOT EXISTS fk_Film_genre_genre_id FOREIGN KEY (genre_id)
        REFERENCES Genres (genre_id);

ALTER TABLE Film_likes
    ADD CONSTRAINT IF NOT EXISTS fk_Film_likes_film_id FOREIGN KEY (film_id)
        REFERENCES Films (film_id);

ALTER TABLE Film_likes
    ADD CONSTRAINT IF NOT EXISTS fk_Film_likes_user_id FOREIGN KEY (user_id)
        REFERENCES Users (user_id);
